a= "CTCGAAGTCAACTGCCGATAACTGAGACCTCTTGGAACTCCACGGGTTTCGCGCCCCTTCCGTCCAAACCTAACCCGTATTGAGAACGTATGCCTCCTCCAGTCACGCGACGTGTACCGCAGTGTGGAGGCTTGGCGAAGCGCCCGACAAGAAGCCTTCTTACTCCCCTAACTCTTAACTGAGAAAAAACTTGGGGCAAGACCGGGTCGCAGTGTGTGAACTGATATGTGGTGTCAAGTTGGGTTAGTCAAGCCGTAAGCCAGTATGCTATCGTCGCCTAGTGCATCATATCGAACATTTCTCTGAATGACGATAAACACAAACGTATCACTCGATGAGCCATGAGAAAATCGAGTAGCGTGGAACTGTCTCTAACTGGGAATCTGCACCACAAACCCTCAATAATCAACTACACATGCCGATTCTTGTTAGTTCTGCTTGAGATAAGTGTACTACGTCTTATGTTCATCAACTGATTTTGTTCTAACCGCCTCCAATTGGGAAGACGTAAGAAGTAAGAGTCGTGGGGCTCCAGCCCGCAATGTAGGATGTGGAGTGGATTTGTGACGTATGACTCAACACCGACCGACCAGCACCTTAGGCTGAACGTCGCGACCGCATAATTCCATCATAACGTGTAGTGTCACTCTAGGTTTATGGTGTCAATACCGAAGCCCCCCACCGATATGATAGTAGCGCAGGCATTACGGTGCAGCCTAGGCTGATATGCACGCTGAACGGGTTCATCCGTTAGGATCCTCTTCGAAGTCGGGTGGGACTTATGCTGTAGGGTGTCATTACGGATGGCCTGTCTCTGACAGCGAAGGTTGGGTTATTTTATCTCGCCCCCACTCCCTCACGGAGCATCAC"
lista= []
b={}
def nucleotydes():

    for i in a:
        lista.append(i)

    for i in lista:
        slownik = lista.count(i)
        b[i] = slownik

    return b

print(nucleotydes())

for x in b.values():
  print(x)

print(a.count("A"), a.count("C"), a.count("G"), a.count("T"))



print("dupa"[:3:])