# DNA = list(
#     'TCCCGTCCCGAAAAACATGCCACCCCTCGCTGTCCAGCATTGCCTCGCGTCGTGTTAGCGACGTGGGTGGTGATGAGATCCTGATCAATCTTGCTAGTCCCCAACGAAGTGACTGGGATGCTCCTGATCCCTTGGGAAGTGTAAACTACCAACTCTCGTTAGAATGGAAAATGCGCATATCGGATAAAAACGACCTGTATTTCTAACGGCGATGATGGCCATTCACAGTGGAATGCGTGAAAGTGTGCTACTATCCATGGGGGAGCGCACGGTGTGTGTAGGCCGCAAGCGTGGTGCCTTTAGCCTTAAGGTCGACAACTAGAATCTCTTCGCGCCCACAGCCTAAATTCTATTGACTTATATTTATGTGTCGAGGTGGTACGGGACGGCACATGACGATCGATCGGCAAGCTCGATTGGTAGCAAGACCATGCATCCTGTAATGTCATCATCGGATCTCACACGATTTATGTGAGGCCGGCAAGGCACTGCCGTCATTTGGGGCTTATCTCGAGGGAGCAATCGGGTTGTGCACAGCTATCAGCCCTTGTCGCTTCCGAAGGGTTCATTGTAGCAATGACGCATTGCGCGTGGAGGCGCGAAGGCGCCCCTCAAAGTAGATTGGTTGTTTTCAGCGTTTCCCCGTCGTCTAACCAAGATCCTCCATGAACTACACAATCAATCAACCGCGTCTAGTGTGGAAAAAGTCCACCCCTTGCATTGGGGCAAATATCAAAGGTTACCCGCTAATGTGTAAGTATCTCGGCATCCGAATAGTTAATTAATCTAATAAGTCGGTTAGTGTTGCGCGTTGAACATCAAGGTGGCGCCTCAACAACTTATTGGAACGCCCTTTCCTACACGGAGCTTCGAGGAACAGGCTTAAGCGAGCGAAATATACAACACGTTCATCACAGATCTTCTAGAACCGTAGCAACCCGTCGTACAACGCGCTGTTTTCGTTATTATAGTAT')
# RNA = []
# for i in DNA:
#     if i == 'A':
#         RNA.append('U')
#     elif i == 'T':
#         RNA.append('A')
#     elif i == 'C':
#         RNA.append('G')
#     elif i == 'G':
#         RNA.append('C')
#     else:
#         RNA.append('?')
#
# RNAA = ''.join(RNA)
# print(RNAA)


class Ciasto():
    def __init__(self, nadzienie = 'czekolada'):
        self.wielkosc_dziurki = 5
        self.czy_ma_posypke = 1
        self.nadzienie = nadzienie

    def zmien_nadzienie( self, nowe_nadzienie):
        self.nadzienie = nowe_nadzienie

ciasto_a = Ciasto( 'truskawka' )
print(ciasto_a.nadzienie)

































